# [[plugins]]
# repo = 'skywind3000/asyncrun.vim'
# hook_add = '''
#     noremap <Leader>at :AsyncRun ./test.sh<CR>
# '''
#
# [[plugins]]
# repo = 'neovim/nvim-lspconfig'
# 
# [[plugins]]
# repo = 'JuliaEditorSupport/julia-vim'

[[plugins]]
repo = 'easymotion/vim-easymotion'

[[plugins]]
repo = 'tpope/vim-rhubarb'

[[plugins]]
repo = 'mechatroner/rainbow_csv'

[[plugins]]
repo = 'chrisbra/Colorizer'

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'

# Commands are copied from https://github.com/junegunn/fzf.vim/blob/9ceac718026fd39498d95ff04fa04d3e40c465d7/plugin/fzf.vim#L47-L69
[[plugins]]
repo = 'junegunn/fzf.vim'
depends = [ 'junegunn/fzf' ]
hook_add = '''
    let $FZF_DEFAULT_OPTS="--layout=reverse"

    command!      -bang -nargs=? -complete=dir TmuxFiles       call fzf#vim#files(<q-args>, fzf#vim#with_preview({'tmux': '-p80%'}), <bang>0)',
    command!      -bang -nargs=? TmuxGitFiles                  call fzf#vim#gitfiles(<q-args>, fzf#vim#with_preview(<q-args> == "?" ? { "placeholder": "", 'tmux': '-p80%' } : {'tmux': '-p80%'}), <bang>0)',
    command!      -bang -nargs=? TmuxGFiles                    call fzf#vim#gitfiles(<q-args>, fzf#vim#with_preview(<q-args> == "?" ? { "placeholder": "", 'tmux': '-p80%' } : {'tmux': '-p80%'}), <bang>0)',
    command! -bar -bang -nargs=? -complete=buffer TmuxBuffers  call fzf#vim#buffers(<q-args>, fzf#vim#with_preview({ "placeholder": "{1}", 'tmux': '-p80%' }), <bang>0)',
    command!      -bang -nargs=* TmuxAg                        call fzf#vim#ag(<q-args>, fzf#vim#with_preview({'tmux': '-p80%'}), <bang>0)',
    command! -bang -nargs=* TmuxGCGrep call fzf#vim#grep('git grep --line-number -- '.shellescape(expand(<q-args>)), 0, fzf#vim#with_preview({'options': ['--query', expand('<cword>')], 'dir': systemlist('git rev-parse --show-toplevel')[0], 'tmux': '-p80%'}), <bang>0)
    command! -bang -nargs=* TmuxGGrep
      \ call fzf#vim#grep(
      \   'git grep --line-number -- '.shellescape(<q-args>), 0,
      \   fzf#vim#with_preview({'dir': systemlist('git rev-parse --show-toplevel')[0], 'options': '--delimiter : --nth 3..', 'tmux': '-p80%'}), <bang>0)

    noremap <Leader>ff :TmuxFiles<CR>
    noremap <Leader>fgf :TmuxGFiles<CR>
    noremap <Leader>fgg :TmuxGGrep<CR>
    noremap <Leader>fgc :TmuxGCGrep<CR>
    noremap <Leader>fa :TmuxAg<CR>
    noremap <Leader>fb :TmuxBuffers<CR>
'''

[[plugins]]
repo = 'antoinemadec/coc-fzf'
depends = [ 'neoclide/coc.nvim' ]
hook_add = '''
    let g:coc_fzf_opts = ['--layout=reverse']
    let g:coc_fzf_preview = 'right:50%'
    noremap <Leader>fs :CocFzfList symbols<CR>
'''

[[plugins]]
repo = 'pboettch/vim-cmake-syntax'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
    let NERDTreeShowHidden = 1
'''

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'
hook_add = '''
    noremap <Leader>nt :NERDTreeTabsToggle<CR>
    noremap <Leader>nf :NERDTreeFind<CR>
'''
depends = ['nerdtree']

[[plugins]]
repo = 'preservim/tagbar'
hook_add = '''
    nmap <C-t> :TagbarToggle<CR>
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'tyru/caw.vim.git'
hook_add = '''
    nmap <C-c> <Plug>(caw:hatpos:toggle)
    vmap <C-c> <Plug>(caw:hatpos:toggle)
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
    " Use powerline-style font
    set laststatus=2
    let g:airline_powerline_fonts = 1
    let g:airline#extensions#tabline#enabled = 1
    let g:airline#extensions#tabline#buffer_idx_mode = 1
    let g:airline#extensions#whitespace#mixed_indent_algo = 1
    let g:airline_theme = 'tomorrow'
    if !exists('g:airline_symbols')
      let g:airline_symbols = {}
    endif
    
    " unicode symbols
    let g:airline_left_sep = '¬ª'
    let g:airline_left_sep = '‚ñ∂'
    let g:airline_right_sep = '¬´'
    let g:airline_right_sep = '‚óÄ'
    let g:airline_symbols.crypt = 'üîí'
    let g:airline_symbols.linenr = '‚ò∞'
    let g:airline_symbols.linenr = '‚êä'
    let g:airline_symbols.linenr = '‚ê§'
    let g:airline_symbols.linenr = '¬∂'
    let g:airline_symbols.maxlinenr = ''
    let g:airline_symbols.maxlinenr = '„èë'
    let g:airline_symbols.branch = '‚éá'
    let g:airline_symbols.paste = 'œÅ'
    let g:airline_symbols.paste = '√û'
    let g:airline_symbols.paste = '‚à•'
    let g:airline_symbols.spell = 'Íû®'
    let g:airline_symbols.notexists = '‚àÑ'
    let g:airline_symbols.whitespace = 'Œû'
    
    " powerline symbols
    let g:airline_left_sep = 'ÓÇ∞'
    let g:airline_left_alt_sep = 'ÓÇ±'
    let g:airline_right_sep = 'ÓÇ≤'
    let g:airline_right_alt_sep = 'ÓÇ≥'
    let g:airline_symbols.branch = 'ÓÇ†'
    let g:airline_symbols.readonly = 'ÓÇ¢'
    let g:airline_symbols.linenr = '‚ò∞'
    let g:airline_symbols.maxlinenr = 'ÓÇ°'
'''

[[plugins]]
repo = 'rust-lang/rust.vim'

# ========== start cpp ==========

# Jump to the corresponding header or source file
[[plugins]]
repo = 'vim-scripts/a.vim'
on_ft = ['c', 'cpp']
hook_source = '''
    nmap <silent> <leader>aa :A<CR>
'''

# ========== end cpp ==========

# ========== start coc ==========

[[plugins]]
repo = 'neoclide/coc.nvim'
merged = 0
rev = 'release'
hook_add = '''
" default install
let g:coc_global_extensions = [
    \'coc-clangd',
    \'coc-rust-analyzer',
    \'coc-pyright',
    \]

" Color of Error and Warning
highlight CocErrorSign ctermfg=15 ctermbg=196
highlight CocWarningSign ctermfg=0 ctermbg=172

" Jump to the definition with \-d
nnoremap <silent> <Leader>d :call CocAction('jumpDefinition')<CR>
" Run format with \-fmt
nnoremap <silent> <Leader>fmt :call CocAction('format')<CR>
" Coc-quick-fix
nnoremap <silent> <Leader>fx :call CocAction('doQuickfix')<CR>

" Use K to show documentation in preview window
nnoremap <silent> <Leader>K :call <SID>show_documentation()<CR>

function! s:show_documentation()
  if (index(['vim','help'], &filetype) >= 0)
    execute 'h '.expand('<cword>')
  else
    call CocAction('doHover')
  endif
endfunction
'''

# ========== end coc ==========
