[[plugins]]
repo = 'JuliaEditorSupport/julia-vim'

[[plugins]]
repo = 'neovim/nvim-lspconfig'
hook_add = '''
lua << EOF
    require'lspconfig'.julials.setup{}
EOF
'''

[[plugins]]
repo = 'mechatroner/rainbow_csv'

[[plugins]]
repo = 'chrisbra/Colorizer'

[[plugins]]
repo = 'davidhalter/jedi-vim'

[[plugins]]
repo = 'tell-k/vim-autopep8'

[[plugins]]
repo = 'vim-scripts/a.vim'
on_ft = ['c', 'cpp']
hook_source = '''
    nmap <silent> <leader>aa :A<CR>
'''

[[plugins]]
repo = 'junegunn/fzf'
build = './install --all'

[[plugins]]
repo = 'junegunn/fzf.vim'
depends = [ 'junegunn/fzf' ]
hook_add = '''
    noremap <Leader>ff :Files<CR>
    noremap <Leader>fgf :GFiles<CR>
    noremap <Leader>fgg :GGrep<CR>
    noremap <Leader>fa :Ag<CR>
    noremap <Leader>fb :Buffers<CR>
'''

[[plugins]]
repo = 'pboettch/vim-cmake-syntax'

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add = '''
    let NERDTreeShowHidden = 1
'''

[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'
hook_add = '''
    noremap <Leader>nt :NERDTreeTabsToggle<CR>
    noremap <Leader>nf :NERDTreeFind<CR>
'''
depends = ['nerdtree']

[[plugins]]
repo = 'preservim/tagbar'
hook_add = '''
    nmap <C-t> :TagbarToggle<CR>
'''

[[plugins]]
repo = 'airblade/vim-gitgutter'

[[plugins]]
repo = 'rhysd/vim-clang-format'
hook_add = '''
    let g:clang_format#detect_style_file = 1
    let g:clang_format#auto_format = 1
'''

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'tyru/caw.vim.git'
hook_add = '''
    nmap <C-c> <Plug>(caw:hatpos:toggle)
    vmap <C-c> <Plug>(caw:hatpos:toggle)
'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'dhruvasagar/vim-table-mode'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'deoplete-plugins/deoplete-clang'
hook_add = '''
    let g:deoplete#sources#clang#libclang_path = '/usr/lib/libclang.so'
    let g:deoplete#sources#clang#clang_header = '/usr/include/clang'
'''
depends = ['deoplete.nvim']

[[plugins]]
repo = 'Shougo/neoinclude.vim'
on_ft = ['c', 'cpp']
depends = ['deoplete.nvim']

[[plugins]]
repo = 'lyuts/vim-rtags'
on_ft = ['c', 'cpp']
hook_add = '''
    let g:rtagsUseDefaultMappings = 0
    let g:rtagsAutoLaunchRdm = 1
'''
hook_source = '''
'''

[[plugins]]
repo = 'w0rp/ale'
hook_add = '''
    let g:ale_sign_column_always = 1
    let g:ale_fix_on_save = 1
    let g:ale_completion_enabled = 0

    let g:ale_sign_error = '‚®â'
    let g:ale_sign_warning = '‚ö†'

    let g:ale_echo_msg_format = '[%linter%] %s [%severity%]'
    let g:ale_statusline_format = ['‚®â %d', '‚ö† %d', '‚¨• ok']
    let g:ale_linters = {
        \   'c' : ['clangd'],
        \   'cpp' : ['clangd']
    \}
'''

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
    " Use powerline-style font
    set laststatus=2
    let g:airline_powerline_fonts = 1
    let g:airline#extensions#tabline#enabled = 1
    let g:airline#extensions#tabline#buffer_idx_mode = 1
    let g:airline#extensions#whitespace#mixed_indent_algo = 1
    let g:airline_theme = 'tomorrow'
    if !exists('g:airline_symbols')
      let g:airline_symbols = {}
    endif
    
    " unicode symbols
    let g:airline_left_sep = '¬ª'
    let g:airline_left_sep = '‚ñ∂'
    let g:airline_right_sep = '¬´'
    let g:airline_right_sep = '‚óÄ'
    let g:airline_symbols.crypt = 'üîí'
    let g:airline_symbols.linenr = '‚ò∞'
    let g:airline_symbols.linenr = '‚êä'
    let g:airline_symbols.linenr = '‚ê§'
    let g:airline_symbols.linenr = '¬∂'
    let g:airline_symbols.maxlinenr = ''
    let g:airline_symbols.maxlinenr = '„èë'
    let g:airline_symbols.branch = '‚éá'
    let g:airline_symbols.paste = 'œÅ'
    let g:airline_symbols.paste = '√û'
    let g:airline_symbols.paste = '‚à•'
    let g:airline_symbols.spell = 'Íû®'
    let g:airline_symbols.notexists = '‚àÑ'
    let g:airline_symbols.whitespace = 'Œû'
    
    " powerline symbols
    let g:airline_left_sep = 'ÓÇ∞'
    let g:airline_left_alt_sep = 'ÓÇ±'
    let g:airline_right_sep = 'ÓÇ≤'
    let g:airline_right_alt_sep = 'ÓÇ≥'
    let g:airline_symbols.branch = 'ÓÇ†'
    let g:airline_symbols.readonly = 'ÓÇ¢'
    let g:airline_symbols.linenr = '‚ò∞'
    let g:airline_symbols.maxlinenr = 'ÓÇ°'
'''

[[plugins]]
repo = 'davidhalter/jedi-vim'

[[plugins]]
repo = 'tell-k/vim-autopep8'
